CREATE TABLE BOOTSTRAP(
    ID SMALLSERIAL NOT NULL,
    HAS_RUN boolean
);

CREATE TABLE REGION(
    ID SMALLSERIAL NOT NULL,
    EVE_REGION_ID INT UNIQUE NOT NULL ON DELETE CASCADE,
    DESCRIPTION TEXT NOT NULL,
    NAME VARCHAR(256) NOT NULL,
    PRIMARY KEY(ID,EVE_REGION_ID)
);

CREATE TABLE CONSTELLATION(
    ID SMALLSERIAL NOT NULL,
    EVE_CONSTELLATION_ID INT UNIQUE NOT NULL,
    EVE_REGION_ID INT REFERENCES REGION(EVE_REGION_ID) ON DELETE CASCADE,
    NAME VARCHAR(256) NOT NULL,
    PRIMARY KEY(ID,EVE_CONSTELLATION_ID)
);

CREATE TABLE SYSTEM(
    ID SMALLSERIAL NOT NULL,
    EVE_CONSTELLATION_ID INT REFERENCES CONSTELLATION (EVE_CONSTELLATION_ID) ON DELETE CASCADE,
    EVE_SYSTEM_ID INT UNIQUE NOT NULL,
    NAME VARCHAR(256) NOT NULL,
    SECURITY_STATUS DECIMAL NOT NULL,
    PRIMARY KEY(ID, EVE_SYSTEM_ID)
);
CREATE TABLE STATION(
    ID SMALLSERIAL NOT NULL,
    NAME VARCHAR(256) NOT NULL,
    EVE_STATION_ID BIGINT UNIQUE NOT NULL,
    EVE_SYSTEM_ID INT REFERENCES SYSTEM (EVE_SYSTEM_ID) ON DELETE CASCADE,
    PRIMARY KEY(ID,EVE_STATION_ID)
);


CREATE TABLE ITEM(
    ID SERIAL NOT NULL,
    NAME VARCHAR(256) NOT NULL,
    TYPE_ID INT UNIQUE NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    PRIMARY KEY(ID,TYPE_ID)
);

CREATE TABLE MARKET_ORDER(
    ID SERIAL NOT NULL,
    DURATION INT NOT NULL,
    IS_BUY_ORDER BOOLEAN NOT NULL,
    ISSUED TIMESTAMP NOT NULL,
    LOCATION_ID BIGINT REFERENCES STATION (EVE_STATION_ID),
    MIN_VOLUME INT NOT NULL,
    EVE_ORDER_ID BIGINT UNIQUE NOT NULL,
    PRICE NUMERIC(20,2) NOT NULL,
    RANGE VARCHAR(25) NOT NULL,
    ITEM_TYPE_ID INT REFERENCES ITEM (TYPE_ID),
    VOLUME_REMAIN INT NOT NULL,
    VOLUME_BEGIN INT NOT NULL,
    PRIMARY KEY(ID,EVE_ORDER_ID)

);

CREATE TABLE OPPORTUNITY(
    ID SERIAL PRIMARY KEY NOT NULL,
    PROFIT_PER_ITEM NUMERIC(20,2) NOT NULL,
    VOLUME INT NOT NULL,
    TOTAL_PROFIT NUMERIC(20,2) NOT NULL,
    ITEM_NAME VARCHAR(256),
    ORIGIN VARCHAR(256),
    DESTINATION VARCHAR(256),
    JUMPS INT NOT NULL
);
