CREATE TABLE BOOTSTRAP(
    HAS_RUN boolean
);

CREATE TABLE REGION(
    ID SMALLSERIAL NOT NULL,
    EVE_REGION_ID INT UNIQUE NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    NAME VARCHAR(256) NOT NULL,
    PRIMARY KEY(ID,EVE_REGION_ID)
);

CREATE TABLE CONSTELLATION(
    ID SMALLSERIAL NOT NULL,
    EVE_CONSTELLATION_ID INT UNIQUE NOT NULL,
    EVE_REGION_ID INT NOT NULL,
    NAME VARCHAR(256) NOT NULL,
    PRIMARY KEY(ID,EVE_CONSTELLATION_ID)
);

CREATE TABLE SYSTEM(
    ID SMALLSERIAL NOT NULL,
    EVE_CONSTELLATION_ID INT REFERENCES CONSTELLATION (EVE_CONSTELLATION_ID),
    EVE_SYSTEM_ID INT UNIQUE NOT NULL,
    NAME VARCHAR(256) NOT NULL,
    SECURITY_STATUS DECIMAL NOT NULL,
    PRIMARY KEY(ID, EVE_SYSTEM_ID)
);
CREATE TABLE STATION(
    ID SERIAL NOT NULL,
    NAME VARCHAR(256) NOT NULL,
    EVE_STATION_ID BIGINT UNIQUE NOT NULL,
    EVE_SYSTEM_ID INT REFERENCES SYSTEM (EVE_SYSTEM_ID),
    PRIMARY KEY(ID,EVE_STATION_ID)
);

CREATE TABLE MARKET_GROUP(
    ID SERIAL NOT NULL,
    MARKET_GROUP_ID INT UNIQUE NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    PARENT_GROUP_ID INT,
    PRIMARY KEY(ID,MARKET_GROUP_ID)
);


CREATE TABLE ITEM(
    ID SERIAL NOT NULL,
    GROUP_ID INT REFERENCES MARKET_GROUP (MARKET_GROUP_ID),
    NAME VARCHAR(256) NOT NULL,
    TYPE_ID INT UNIQUE NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    PRIMARY KEY(ID,TYPE_ID)
);

CREATE TABLE MARKET_ORDER(
    ID SERIAL NOT NULL,
    DURATION INT NOT NULL,
    IS_BUY_ORDER BOOLEAN NOT NULL,
    ISSUED TIMESTAMP NOT NULL,
    LOCATION_ID BIGINT REFERENCES STATION (EVE_STATION_ID),
    MIN_VOLUME INT NOT NULL,
    EVE_ORDER_ID BIGINT UNIQUE NOT NULL,
    PRICE MONEY NOT NULL,
    RANGE VARCHAR(25) NOT NULL,
    ITEM_TYPE_ID INT REFERENCES ITEM (TYPE_ID),
    VOLUME_REMAIN INT NOT NULL,
    VOLUME_BEGIN INT NOT NULL,
    PRIMARY KEY(ID,EVE_ORDER_ID)

);
